"""Stable domain contracts shared by long-term memory adapters."""

from agent_runtime.memory.domain.interfaces import (
    MemoryCatalog,
    MemoryConsolidator,
    MemoryDocumentStore,
    LongTermMemoryReader,
    MemoryRetriever,
    MemorySemanticIndex,
    SkillPublisher,
    TaskArchiveStore,
)
from agent_runtime.memory.domain.models import (
    ARCHIVE_SCHEMA_VERSION,
    MEMORY_SCHEMA_VERSION,
    ArchiveFileRecord,
    ConsolidationResult,
    MemoryDocument,
    MemoryEvidence,
    MemoryHit,
    MemoryQuery,
    MemoryRelation,
    MemoryScope,
    MemorySource,
    MemoryStatus,
    MemoryType,
    ScopeLevel,
    SessionMemorySnapshot,
    TaskArchiveManifest,
)

__all__ = [
    "ARCHIVE_SCHEMA_VERSION",
    "MEMORY_SCHEMA_VERSION",
    "ArchiveFileRecord",
    "ConsolidationResult",
    "MemoryCatalog",
    "MemoryConsolidator",
    "MemoryDocument",
    "MemoryDocumentStore",
    "MemoryEvidence",
    "MemoryHit",
    "LongTermMemoryReader",
    "MemoryQuery",
    "MemoryRelation",
    "MemoryRetriever",
    "MemoryScope",
    "MemorySemanticIndex",
    "MemorySource",
    "MemoryStatus",
    "MemoryType",
    "ScopeLevel",
    "SessionMemorySnapshot",
    "SkillPublisher",
    "TaskArchiveManifest",
    "TaskArchiveStore",
]
