"""Storage-independent ports for the durable memory architecture."""

from __future__ import annotations

from collections.abc import Iterable
from pathlib import Path
from typing import Any, Protocol

from model.agent.graph import AgentState

from agent_runtime.memory.domain.models import (
    ConsolidationResult,
    MemoryDocument,
    MemoryHit,
    MemoryQuery,
    TaskArchiveManifest,
)


class TaskArchiveStore(Protocol):
    def archive(
        self,
        state: AgentState,
        trace_path: str | Path = "",
        *,
        session_snapshot: dict[str, Any] | None = None,
    ) -> TaskArchiveManifest: ...
    def load_manifest(self, task_id: str) -> TaskArchiveManifest: ...
    def verify(self, task_id: str) -> list[str]: ...
    def task_path(self, task_id: str) -> Path: ...
    def artifact_path(self, task_id: str, logical_name: str) -> Path: ...
    def read_json_artifact(self, task_id: str, logical_name: str) -> object: ...
    def read_text_artifact(self, task_id: str, logical_name: str) -> str: ...
    def manifest_hash(self, task_id: str) -> str: ...


class MemoryDocumentStore(Protocol):
    def get(self, memory_id: str) -> MemoryDocument | None: ...
    def save(self, document: MemoryDocument) -> Path: ...
    def list(self) -> Iterable[MemoryDocument]: ...
    def records(self) -> Iterable[tuple[MemoryDocument, Path]]: ...
    def deprecate(self, memory_id: str, reason: str) -> None: ...
    def content_hash(self, memory_id: str) -> str: ...


class MemoryCatalog(Protocol):
    def synchronize(self, document: MemoryDocument, document_path: Path) -> None: ...
    def keyword_search(self, query: MemoryQuery) -> list[MemoryHit]: ...
    def rebuild(
        self, documents: Iterable[tuple[MemoryDocument, Path]]
    ) -> Any | None: ...


class MemorySemanticIndex(Protocol):
    def synchronize(self, document: MemoryDocument) -> None: ...
    def semantic_search(self, query: MemoryQuery) -> list[MemoryHit]: ...
    def rebuild(self, documents: Iterable[MemoryDocument]) -> None: ...


class MemoryRetriever(Protocol):
    def retrieve(self, query: MemoryQuery) -> list[MemoryHit]: ...


class LongTermMemoryReader(Protocol):
    """Agent capability boundary: retrieval only, with no persistence methods."""

    def retrieve_if_needed(
        self,
        state: AgentState,
        *,
        phase: str,
        force: bool = False,
    ) -> Any | None: ...


class MemoryConsolidator(Protocol):
    def consolidate(self, task_id: str) -> ConsolidationResult: ...


class SkillPublisher(Protocol):
    def evaluate(self, memories: list[MemoryDocument]) -> object | None: ...
    def publish(self, candidate: object) -> Path: ...
